[package]
name = "serde_fbx"
version = "0.1.0"
description = "Convert FBX animations into Havok HKX animations."

authors.workspace = true
categories = ["development-tools"]
edition.workspace = true
keywords = ["skyrim"]
license = "GPL-3.0"
readme = "../../README.md"
repository.workspace = true
rust-version.workspace = true

[dependencies]
rayon = { workspace = true }                    # Parallel
serde = { workspace = true }
snafu = { workspace = true }                    # Define all error patterns(with backtrace)
tracing = { workspace = true, optional = true }
ufbx = "0.11.3"

# serde-hkx
havok_classes = { workspace = true, features = ["ignore_duplicates"] }
havok_serde = { workspace = true }
havok_types = { workspace = true, features = ["serde"] }
serde_hkx = { workspace = true }
serde_hkx_features = { workspace = true }

# workspace members
serde_spline = { path = "../serde_spline" }
ufbx_write = { path = "../ufbx_write" }

[dev-dependencies]
quick_tracing = { workspace = true }
serde_hkx = { workspace = true, features = ["tracing"] }
tracing = { workspace = true }
egui = "0.36"
eframe = "0.36"
sonic-rs = { version = "0.5.8" }

[features]
# Enable tracing logging
tracing = ["dep:tracing", "serde_hkx/tracing", "serde_spline/tracing"]


[lints]
workspace = true
